name: transmission
base: core24
adopt-info: transmission
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:

slots:
  transmission:
    interface: dbus
    bus: session
    name: com.transmissionbt.transmission

apps:
  transmission:
    command: usr/bin/transmission-gtk
    extensions: [gnome]
    common-id: com.transmissionbt.transmission
    desktop: usr/share/applications/transmission-gtk.desktop
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control

parts:
  transmission:
    source: https://github.com/transmission/transmission.git
    source-depth: 1
    source-tag: '4.0.6'
    plugin: cmake
    parse-info: [usr/share/metainfo/transmission-gtk.metainfo.xml]
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DENABLE_DAEMON=OFF
      - -DINSTALL_DOC=OFF
      - -DENABLE_UTILS=OFF
      - -DINSTALL_WEB=OFF
    build-packages:
      - libcurl4-openssl-dev
      - libminiupnpc-dev
      - libssl-dev
      - libnatpmp-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
      sed -e 's|Icon=transmission|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/transmission.svg|' -i gtk/transmission-gtk.desktop.in
      sed -i '50d' gtk/transmission-gtk.metainfo.xml.in

  deps:
    after: [transmission]
    plugin: nil
    stage-packages:
      - libminiupnpc17
      - libnatpmp1
    prime:
      - usr/lib/*/libminiupnpc*
      - usr/lib/*/libnatpmp*
